#!/usr/bin/env python3
#coding=utf-8

from aliyunsdkcore.client import AcsClient
from aliyunsdkcore.acs_exception.exceptions import ClientException
from aliyunsdkcore.acs_exception.exceptions import ServerException
from aliyunsdkcdn.request.v20180510.SetDomainServerCertificateRequest import SetDomainServerCertificateRequest

client = AcsClient('<accessKeyId>', '<accessSecret>', 'cn-shanghai')

request = SetDomainServerCertificateRequest()
request.set_accept_format('json')

request.set_DomainName(".xn--yd3az4rn1c.live")
request.set_ServerCertificateStatus("on")
request.set_CertName("wxs-wildcard")
request.set_CertType("upload")
request.set_ServerCertificate("")
request.set_PrivateKey("")
request.set_ForceSet("1")

response = client.do_action_with_exception(request)
print(str(response, encoding='utf-8'))
