# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CertUpdate

on:
  schedule:
    - cron: 0 0 1 */2 *

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update Aliyun CDN certificate.
      env:
        DOMAIN: ${{ secrets.DOMAIN }}
        ACCESSKEYID: ${{ secrets.ACCESSKEYID }}
        ACCESSSECRET: ${{ secrets.ACCESSSECRET }}
        PRIVATEKEY: ${{ secrets.PRIVATEKEY }}
      run: |
        curl https://get.acme.sh | sh
        echo -e "SAVED_Ali_Key='${ACCESSKEYID}'" > ~/.acme.sh/account.conf
        echo -e "SAVED_Ali_Secret='${ACCESSSECRET}'" >> ~/.acme.sh/account.conf
        echo -e "USER_PATH=${PATH}" >> ~/.acme.sh/account.conf
        mkdir -p ~/.acme.sh/${DOMAIN}_ecc/
        echo -e "${PRIVATEKEY}" >> ~/.acme.sh/${DOMAIN}_ecc/${DOMAIN}.key
        cp ${DOMAIN}.conf ~/.acme.sh/${DOMAIN}_ecc/
        CHALLENGE=$(~/.acme.sh/acme.sh --issue -d ${DOMAIN} -d *.${DOMAIN} --dns -k ec-384 --yes-I-know-dns-manual-mode-enough-go-ahead-please --renew --ecc --force | grep TXT\ value | cut -d \' -f 2)
        python addTXT.py $CHALLENGE
        sleep 30
        ~/.acme.sh/acme.sh --issue -d ${DOMAIN} -d *.${DOMAIN} --dns -k ec-384 --yes-I-know-dns-manual-mode-enough-go-ahead-please --renew --ecc --force
        python main.py
        python deleteTXT.py
    - name: Update repo.
      env:
        DOMAIN: ${{ secrets.DOMAIN }}
      run: |
        rm -rf ${DOMAIN}.conf ${DOMAIN}.cer
        cp ~/.acme.sh/${DOMAIN}_ecc/${DOMAIN}.conf ./
        cp ~/.acme.sh/${DOMAIN}_ecc/fullchain.cer ./${DOMAIN}.cer
        git config --global user.name 'Actions'
        git config --global user.email 'capric98@users.noreply.github.com'
        if [ -n "$(git status --porcelain)" ]; then
            git commit -am "Update cert config file by actions."
        fi
        git push
