# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CertUpdate

on:
  schedule:
    - cron: 0 0 1 */2 *

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: curl
      uses: wei/curl@v1
      with:
        args: --output ~/install-acme.sh https://get.acme.sh
    - name: Run acme.sh
      run: |
        sh ~/install-acme.sh
        echo -e "SAVED_Ali_Key='${ACCESSKEYID}'" > ~/.acme.sh/account.conf
        echo -e "SAVED_Ali_Secret='${ACCESSSECRET}'" >> ~/.acme.sh/account.conf
        echo -e "USER_PATH=${PATH}" >> ~/.acme.sh/account.conf
        mkdir -p ~/.acme.sh/${DOMAIN}_ecc/${DOMAIN}.key
        echo -e ${PRIVATEKEY} >> ~/.acme.sh/${DOMAIN}_ecc/
        ~/.acme.sh/acme.sh --force --renew-all -k ec-384
    - name: Update Aliyun CDN certificate.
      run: |
        python main.py
